### ISSUE TITLE
Getting end of stream error on xlsx file

### ISSUE THREAD

**Issue by gmannGlasswall** [filetrust/mvp-glasswall-file-drop#10]
When processing the file in the link below I get the following issue reported that stops the file being regenerated "End of stream 'workbook.xml' not reached". Wanting to see what was going wrong with this file I ran through CLI on the latest version of the SDK. However it did not report the end of stream issue.

[Greg Mann ITC 2020.xlsx](https://github.com/filetrust/mvp-glasswall-file-drop/files/4164430/Greg.Mann.ITC.2020.xlsx)

**Comment by Diggers89** [comment]
File drop was previously using Core 1. 

Issue has now been resolved as the back-end is now using Core 2.
