### ISSUE TITLE
Create Zip file with all XML report files from File Drop MVP

### ISSUE THREAD

**Issue by DinisCruz** [filetrust/mvp-glasswall-file-drop#4]
Hi @lukeR4 based on  https://twitter.com/LukeRobbertse/status/1218461557153239040 I'm assigning this to you :)

![image](https://user-images.githubusercontent.com/656739/72662825-ab266100-39e3-11ea-8a23-ccd4d359c661.png)

**Comment by lukeR4** [comment]
I've created a batch file which can do this. Just the path's will need to be edited in the file.
The batch file uses powershell and AZ CLI to download the blobs to a local path and then zip them up. Some engineering will be needed if we want to upload that zip back to github.

**Comment by lukeR4** [comment]
mvp-glasswall-file-drop/reports/analysisreports.zip
