### ISSUE TITLE
Add links and more details to the main File Drop page

### ISSUE THREAD

**Issue by DinisCruz** [filetrust/mvp-glasswall-file-drop#5]
At the moment it looks like this
![image](https://user-images.githubusercontent.com/656739/72681316-4e34b480-3a90-11ea-8f1d-fadd9a2610dc.png)

We should be adding
- links to main GW website
- links to GitHub repo
- explanation of what it does and how it works
- links to relevant posts like https://medium.com/glasswall-engineering/using-glasswall-engine-to-protect-file-uploads-f3e79815e356 and https://medium.com/glasswall-engineering/glasswall-has-a-new-kid-on-the-block-e5c6feb511
- links to pricing
- what is coming next (API Keys, Threat Intelligence reports)
- ability to register to get updates (and to be invited to our MVP test group)

**Comment by asadikhlas** [comment]
I'd love to give this one a look. That is, if no one else is already working on it.
